name: CI

on:
  push:
  workflow_dispatch:

jobs:
  prettify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.CI_PERSONAL_TOKEN }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.PRIVATE_KEY_CI }}
          passphrase: ${{ secrets.PASSWORD_KEY_CI }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install node dependencies
        run: npm ci

      - name: Run Prettier
        run: npx prettier --write .

      - name: Commit changes
        run: |
          git config --global user.name 'robotcoralci'
          git config --global user.email 'robotcoralci@users.noreply.github.com'
          git add -A
          if [ $(git diff --name-only --cached) ]; then git commit -S -m "chore: run Prettier"; fi          
          git push

  build:
    runs-on: ubuntu-latest
    needs: [prettify]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install python dependencies
        run: pip install -r source/requirements.txt

      - name: Install LaTex
        run: sudo apt-get install -y texlive texlive-lang-german texlive-xetex latexmk fonts-freefont-otf

      - name: Build html documentation
        run: make html SPHINXOPTS="-W --keep-going -n"

      - name: Build LaTex documentation
        run: make latexpdf SPHINXOPTS="-W --keep-going -n"
