name: CI

on:
  pull_request:
  push:

  workflow_dispatch:

jobs:
  prettify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_PERSONAL_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install node dependencies
        run: npm ci

      - name: Run Prettier
        run: npx prettier --write .

      - name: Commit changes
        run: |
          git config --global user.name 'robotcoralci'
          git config --global user.email 'robotcoralci@users.noreply.github.com'
          git add -A
          if [ $(git diff --name-only --cached) ]; then git commit -m "chore: run Prettier"; fi          
          git push

  build:
    runs-on: ubuntu-latest
    needs: [prettify]

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_PERSONAL_TOKEN }}

      - uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Version range or exact version of a Python version to use, using SemVer's version range syntax

      - name: Install python dependencies
        run: pip install -r source/requirements.txt

      - name: Install LaTex
        run: sudo apt-get install -y texlive texlive-lang-german texlive-xetex latexmk fonts-freefont-otf

      - name: Build html documentation
        run: make html SPHINXOPTS="-W --keep-going -n"

      - name: Build LaTex documentation
        run: make latexpdf SPHINXOPTS="-W --keep-going -n"
