name: Version sync

on:
  repository_dispatch:
    types: [sync_version]

  workflow_dispatch:

jobs:
  sync_version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_PERSONAL_TOKEN }}

      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install python dependencies
        run: |
          pip install requests
          pip install -r source/requirements.txt

      - name: Install LaTex
        run: sudo apt-get install -y texlive texlive-lang-german texlive-xetex latexmk fonts-freefont-otf

      - name: Sync version with coral-app
        run: python3 bumpversion.py

      - name: Commit changes
        run: |
          git config --global user.name 'robotcoralci'
          git config --global user.email 'robotcoralci@users.noreply.github.com'
          git commit -am "chore: bump version to $(cat doc_version.txt)"
          git push

      - name: Create Release strings
        id: release_strings
        run: |
          echo "RELEASE_TAG=$(cat doc_version.txt)" >> $GITHUB_ENV
          echo "RELEASE_NAME=Version $(cat doc_version.txt)" >> $GITHUB_ENV

      - name: Build release files
        run: ./build_release.sh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_NAME }}
          files: |
            "Robot-Coral-docs-${{ env.RELEASE_TAG }}.pdf"
            "Robot-Coral-docs-${{ env.RELEASE_TAG }}.zip"
