name: Version sync

on:
  repository_dispatch:
    types: [sync_version]

  workflow_dispatch:

jobs:
  sync_version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_PERSONAL_TOKEN }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.PRIVATE_KEY_CI }}
          passphrase: ${{ secrets.PASSWORD_KEY_CI }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install python dependencies
        run: |
          pip install requests
          pip install -r source/requirements.txt

      - name: Install LaTex
        run: sudo apt-get install -y texlive texlive-lang-german texlive-xetex latexmk fonts-freefont-otf

      - name: Sync version with coral-app
        run: python3 bumpversion.py

      - name: Commit changes
        run: |
          git config --global user.name 'robotcoralci'
          git config --global user.email 'robotcoralci@users.noreply.github.com'
          git add -A
          echo -e "\ngit diff:"
          echo "$(git diff --name-only --cached)"
          if [ "$(git diff --name-only --cached)" ]; then git commit -S -m "chore: bump version to $(cat doc_version.txt)"; git push; fi

      - name: Create release strings
        id: release_strings
        run: |
          echo "RELEASE_TAG=$(cat doc_version.txt)" >> $GITHUB_ENV
          echo "RELEASE_NAME=Version $(cat doc_version.txt)" >> $GITHUB_ENV

      - name: Build release files
        run: ./build_release.sh

      - name: Create release file names
        run: |
          echo "PDF_FILENAME=Robot-Coral-docs-${{ env.RELEASE_TAG }}.pdf" >> $GITHUB_ENV
          echo "ZIP_FILENAME=Robot-Coral-docs-${{ env.RELEASE_TAG }}.zip" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_NAME }}
          files: |
            ${{ env.PDF_FILENAME }}
            ${{ env.ZIP_FILENAME }}
