name: Version sync

on:
  repository_dispatch:
    types: [sync_version]

  workflow_dispatch:

jobs:
  sync_version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_PERSONAL_TOKEN }}

      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      
      - name: Install python dependencies
        run: pip install requests

      - name: Sync version with coral-app
        run: python3 bumpversion.py

      - name: Commit changes
        run: |
          git config --global user.name 'robotcoralci'
          git config --global user.email 'robotcoralci@users.noreply.github.com'
          git commit -am "chore: bump version to ${{ github.event.inputs.version }}"
          git push

      - name: Create Release strings
        id: release_strings
        run: |
          echo "RELEASE_TAG=$(cat doc_version.txt)" >> $GITHUB_ENV
          echo "RELEASE_NAME=Version $(cat doc_version.txt)" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_NAME }}
